//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjExercicio13.wsPais {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPais.wsPaisSoap")]
    public interface wsPaisSoap {
        
        // CODEGEN: Parameter 'clsPais' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmIncluir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PrjExercicio13.wsPais.wmIncluirResponse wmIncluir(PrjExercicio13.wsPais.wmIncluirRequest request);
        
        // CODEGEN: Parameter 'clsPais' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmAtualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PrjExercicio13.wsPais.wmAtualizarResponse wmAtualizar(PrjExercicio13.wsPais.wmAtualizarRequest request);
        
        // CODEGEN: Parameter 'clsPais' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmExcluir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PrjExercicio13.wsPais.wmExcluirResponse wmExcluir(PrjExercicio13.wsPais.wmExcluirRequest request);
        
        // CODEGEN: Parameter 'clsPais' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wmSelecionar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PrjExercicio13.wsPais.wmSelecionarResponse wmSelecionar(PrjExercicio13.wsPais.wmSelecionarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsPais : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cdPaisField;
        
        private string dsPaisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CdPais {
            get {
                return this.cdPaisField;
            }
            set {
                this.cdPaisField = value;
                this.RaisePropertyChanged("CdPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DsPais {
            get {
                return this.dsPaisField;
            }
            set {
                this.dsPaisField = value;
                this.RaisePropertyChanged("DsPais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmIncluir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wmIncluirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PrjExercicio13.wsPais.clsPais clsPais;
        
        public wmIncluirRequest() {
        }
        
        public wmIncluirRequest(PrjExercicio13.wsPais.clsPais clsPais) {
            this.clsPais = clsPais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmIncluirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wmIncluirResponse {
        
        public wmIncluirResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmAtualizar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wmAtualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PrjExercicio13.wsPais.clsPais clsPais;
        
        public wmAtualizarRequest() {
        }
        
        public wmAtualizarRequest(PrjExercicio13.wsPais.clsPais clsPais) {
            this.clsPais = clsPais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmAtualizarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wmAtualizarResponse {
        
        public wmAtualizarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmExcluir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wmExcluirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PrjExercicio13.wsPais.clsPais clsPais;
        
        public wmExcluirRequest() {
        }
        
        public wmExcluirRequest(PrjExercicio13.wsPais.clsPais clsPais) {
            this.clsPais = clsPais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmExcluirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wmExcluirResponse {
        
        public wmExcluirResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmSelecionar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wmSelecionarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PrjExercicio13.wsPais.clsPais clsPais;
        
        public wmSelecionarRequest() {
        }
        
        public wmSelecionarRequest(PrjExercicio13.wsPais.clsPais clsPais) {
            this.clsPais = clsPais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmSelecionarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wmSelecionarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet wmSelecionarResult;
        
        public wmSelecionarResponse() {
        }
        
        public wmSelecionarResponse(System.Data.DataSet wmSelecionarResult) {
            this.wmSelecionarResult = wmSelecionarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsPaisSoapChannel : PrjExercicio13.wsPais.wsPaisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsPaisSoapClient : System.ServiceModel.ClientBase<PrjExercicio13.wsPais.wsPaisSoap>, PrjExercicio13.wsPais.wsPaisSoap {
        
        public wsPaisSoapClient() {
        }
        
        public wsPaisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsPaisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPaisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPaisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrjExercicio13.wsPais.wmIncluirResponse PrjExercicio13.wsPais.wsPaisSoap.wmIncluir(PrjExercicio13.wsPais.wmIncluirRequest request) {
            return base.Channel.wmIncluir(request);
        }
        
        public void wmIncluir(PrjExercicio13.wsPais.clsPais clsPais) {
            PrjExercicio13.wsPais.wmIncluirRequest inValue = new PrjExercicio13.wsPais.wmIncluirRequest();
            inValue.clsPais = clsPais;
            PrjExercicio13.wsPais.wmIncluirResponse retVal = ((PrjExercicio13.wsPais.wsPaisSoap)(this)).wmIncluir(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrjExercicio13.wsPais.wmAtualizarResponse PrjExercicio13.wsPais.wsPaisSoap.wmAtualizar(PrjExercicio13.wsPais.wmAtualizarRequest request) {
            return base.Channel.wmAtualizar(request);
        }
        
        public void wmAtualizar(PrjExercicio13.wsPais.clsPais clsPais) {
            PrjExercicio13.wsPais.wmAtualizarRequest inValue = new PrjExercicio13.wsPais.wmAtualizarRequest();
            inValue.clsPais = clsPais;
            PrjExercicio13.wsPais.wmAtualizarResponse retVal = ((PrjExercicio13.wsPais.wsPaisSoap)(this)).wmAtualizar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrjExercicio13.wsPais.wmExcluirResponse PrjExercicio13.wsPais.wsPaisSoap.wmExcluir(PrjExercicio13.wsPais.wmExcluirRequest request) {
            return base.Channel.wmExcluir(request);
        }
        
        public void wmExcluir(PrjExercicio13.wsPais.clsPais clsPais) {
            PrjExercicio13.wsPais.wmExcluirRequest inValue = new PrjExercicio13.wsPais.wmExcluirRequest();
            inValue.clsPais = clsPais;
            PrjExercicio13.wsPais.wmExcluirResponse retVal = ((PrjExercicio13.wsPais.wsPaisSoap)(this)).wmExcluir(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrjExercicio13.wsPais.wmSelecionarResponse PrjExercicio13.wsPais.wsPaisSoap.wmSelecionar(PrjExercicio13.wsPais.wmSelecionarRequest request) {
            return base.Channel.wmSelecionar(request);
        }
        
        public System.Data.DataSet wmSelecionar(PrjExercicio13.wsPais.clsPais clsPais) {
            PrjExercicio13.wsPais.wmSelecionarRequest inValue = new PrjExercicio13.wsPais.wmSelecionarRequest();
            inValue.clsPais = clsPais;
            PrjExercicio13.wsPais.wmSelecionarResponse retVal = ((PrjExercicio13.wsPais.wsPaisSoap)(this)).wmSelecionar(inValue);
            return retVal.wmSelecionarResult;
        }
    }
}
